[package]
name = "pawlice-academy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "paws"
path = "src/paws.rs"

[dependencies]
enum-display = "0.1.3"
rand = "0.8.5"
